[package]
name = "spyrrow"
version = "0.1.1"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "spyrrow"
crate-type = ["cdylib"]

[dependencies]
jagua-rs = { git = "https://github.com/JeroenGar/jagua-rs.git", rev="acad15611349bd9ec2cc8cc645db3ca73764afcf"}
pyo3 = "0.24.0"
rand = { version = "0.9.0", features = ["small_rng"] }
sparrow = { git = "https://github.com/JeroenGar/sparrow.git",rev="7cc981b47beca48add01dfcc4bc350b7474dd90b" }


