#!/usr/bin/env python3
"""Generate the type stubs `spyrrow.pyi` from the Rust sources.

The stubs (signatures, types and docstrings) are produced by PyO3's introspection
(`experimental-inspect`, behind the `stubs` cargo feature) through `maturin generate-stubs`.
They must not be edited by hand: document the Rust code with `///` comments instead.

Usage:
    python scripts/generate_stubs.py           # regenerate spyrrow.pyi
    python scripts/generate_stubs.py --check   # exit 1 if spyrrow.pyi is not up to date (CI)

Requires maturin >= 1.15, e.g. `uvx --from "maturin>=1.15" maturin` as MATURIN.
"""
# MARK: stubs-script

import argparse
import difflib
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STUB = ROOT / "spyrrow.pyi"
HEADER = "# Generated by scripts/generate_stubs.py from the Rust sources, do not edit by hand.\n"


def generate() -> str:
    maturin = shlex.split(os.environ.get("MATURIN", "maturin"))
    with tempfile.TemporaryDirectory() as out:
        subprocess.run(
            [*maturin, "generate-stubs", "--quiet", "--features", "stubs", "--out", out],
            cwd=ROOT,
            check=True,
        )
        return HEADER + (Path(out) / "spyrrow" / "__init__.pyi").read_text()


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if spyrrow.pyi differs from the generated stubs")
    args = ap.parse_args()

    stubs = generate()
    current = STUB.read_text() if STUB.exists() else ""
    if args.check:
        if stubs != current:
            sys.stdout.writelines(
                difflib.unified_diff(current.splitlines(True), stubs.splitlines(True), "spyrrow.pyi", "generated")
            )
            sys.exit("spyrrow.pyi is out of date: run `python scripts/generate_stubs.py` and commit the result")
        print("spyrrow.pyi is up to date")
    elif stubs != current:
        STUB.write_text(stubs)
        print("spyrrow.pyi updated")
    else:
        print("spyrrow.pyi already up to date")


if __name__ == "__main__":
    main()
